spring:
  application:
    name: springcloud-enreka-turbine

server:
  port: 8080

management:
  port: 8081

## 服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7397/eureka

## 监控汇总配置，这里配置2个应用逗号隔开
turbine:
  app-config: springcloud-enreka-feign,springcloud-enreka-ribbon
  cluster-name-expression: new String("default")
  combine-host-port: true