server:
  port: 9002

spring:
  application:
    name: springcloud-eureka-ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7373/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream